import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/useAuth';
import { notifyTicketReply } from '../utils/portal';
import './Portal.css';

export default function Admin() {
	const { supabase, user, session } = useAuth();
	const [tickets, setTickets] = useState([]); const [orders, setOrders] = useState([]); const [profiles, setProfiles] = useState([]); const [selected, setSelected] = useState(null); const [messages, setMessages] = useState([]); const [reply, setReply] = useState(''); const [error, setError] = useState('');
	const load = useCallback(async () => { const [t, o, p] = await Promise.all([supabase.from('tickets').select('*').order('updated_at', { ascending: false }), supabase.from('orders').select('*').order('created_at', { ascending: false }).limit(100), supabase.from('profiles').select('id,email,full_name,account_status,created_at').order('created_at', { ascending: false }).limit(100)]); setTickets(t.data || []); setOrders(o.data || []); setProfiles(p.data || []); setError(t.error?.message || o.error?.message || p.error?.message || ''); }, [supabase]);
	useEffect(() => { load(); }, [load]);
	const open = async (ticket) => { setSelected(ticket); const result = await supabase.from('ticket_messages').select('*').eq('ticket_id', ticket.id).order('created_at'); setMessages(result.data || []); };
	const updateStatus = async (status) => { const { error: updateError } = await supabase.from('tickets').update({ status, updated_at: new Date().toISOString() }).eq('id', selected.id); if (updateError) setError(updateError.message); else { setSelected({ ...selected, status }); load(); } };
	const send = async (event) => { event.preventDefault(); const { data: message, error: sendError } = await supabase.from('ticket_messages').insert({ ticket_id: selected.id, author_id: user.id, body: reply.trim() }).select('id').single(); if (sendError) return setError(sendError.message); setReply(''); const notified = await notifyTicketReply(session, { messageId: message.id }); await open(selected); await load(); setError(notified ? '' : 'Reply saved, but the email notification could not be sent.'); };
	return <div className="portal-page"><header className="portal-heading"><div><span className="eyebrow">Staff only</span><h1>Customer operations</h1><p>Manage support and review customer order history.</p></div><Link className="btn btn-secondary" to="/account">Customer account</Link></header>{error && <div className="portal-error" role="alert">{error}</div>}
		<div className="admin-metrics"><div><strong>{tickets.filter((t) => t.status !== 'closed').length}</strong><span>active tickets</span></div><div><strong>{orders.length}</strong><span>recent orders</span></div><div><strong>{profiles.length}</strong><span>customers</span></div></div>
		<div className="portal-grid"><section className="portal-card"><h2>Ticket queue</h2><div className="ticket-list">{tickets.map((ticket) => <button key={ticket.id} onClick={() => open(ticket)} className={selected?.id === ticket.id ? 'active' : ''}><strong>{ticket.subject}</strong><span>{profiles.find((profile) => profile.id === ticket.user_id)?.email || ticket.user_id} · {ticket.status.replaceAll('_', ' ')}</span></button>)}</div></section><section className="portal-card">{selected ? <><div className="ticket-toolbar"><h2>{selected.subject}</h2><select aria-label="Ticket status" value={selected.status} onChange={(e) => updateStatus(e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_for_customer">Waiting for customer</option><option value="closed">Closed</option></select></div><div className="conversation">{messages.map((message) => <div className={message.author_id === user.id ? 'message own' : 'message'} key={message.id}><p>{message.body}</p></div>)}<form onSubmit={send}><textarea value={reply} onChange={(e) => setReply(e.target.value)} maxLength="4000" required /><button className="btn btn-primary">Reply as staff</button></form></div></> : <p>Select a ticket to review its conversation.</p>}</section></div>
		<section className="portal-card"><h2>Recent orders</h2><div className="portal-list">{orders.map((order) => <article key={order.id}><div><strong>{order.customer_email}</strong><p>{order.stripe_session_id} · {order.status}</p></div><strong>{(order.amount_total / 100).toFixed(2)} {order.currency.toUpperCase()}</strong></article>)}</div></section>
	</div>;
}
